name: remane model

on:
workflow_dispatch:
push:
    branches: [test, production]
permissions:
contents: write
jobs:
build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
        uses: actions/checkout@v2

    - name: Rename file in test
        if: github.ref == 'refs/heads/test'
        run: mv models/alcampo_final_dev.model.lkml models/alcampo_final_test.model.lkml
        
    - name: Rename file in production
        if: github.ref == 'refs/heads/production'
        run: mv models/alcampo_final_test.model.lkml models/alcampo_final.model.lkml

    - name: Push Changes
        run: |
        git config --global user.name '[USERNAME]'
        git config --global user.email '[USER_EMAIL]'
        git add -A
        git commit -am "Change filename"
        git push
